# Generated by Django 2.0.3 on 2018-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('items', models.CharField(max_length=128)),
                ('price', models.FloatField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
